Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Gallery
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Alexandra Bulgakova"
  description: ""
  # staticPath: ""  # The path to serve the static files from
  favicon: "./fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "" # Brand name for the brand | default is the title variable
    disableSearch: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hello, I am"
    title: "Alexandra Bulgakova"
    subtitle: ""
    content: |-
      I fly over the cuckoo's nest, enjoy the panorama that opens 🚀

      Days are measured by the number of poems written.<br/>There is one, so the day was not in vain ✍️
    image: ../images/hero.jpg
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "My CV"
      url: "/doc/alexandra-bulgakova-writer.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-instagram
          url: https://www.instagram.com/bipoliarnaya.zvezda/
        - icon: fab fa-linkedin-in
          url: https://www.linkedin.com/in/xandracurtis
       # - icon: fab fa-github
       #   url: https://github.com/tattooedwriter
        # - icon: fab fa-twitter
        #   url: https://example.com
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  about:
    enable: true
    title: "About me"
    image: "/images/about.jpg"
    content: |-
      Ladies, gentlemen and those who are still determining,

      My name is Alexandra Bulgakova and I am a writer, poet and psychologist with a passion for literature, music and philosophy. As a child, I dreamed of drawing and writing piano music, but as Mick Jagger sang, you can't always get what you want, and closer to adulthood I found another way to convey the world through the prism of my own perception - literature.

      I've lived with ADHD and bipolar disorder for 30 years, in the course of which I've expanded the boundaries of the subconscious, achieved mindfulness and gone a little crazy, only to rise back up with renewed strength and knowledge. I would be happy to help you restore your spirit and heal your soul. If you have any questions, feel free to email me. I am also always happy to receive feedback from readers, because for a poet there is nothing more wonderful than to open the window of his subconsciousness and have tea with a random passerby.

      I can say the following about myself: Castaneda didn't believe it, Ian Curtis smoked, Stephen King wrote it down, and Yegor Letov sang along... So I'm flying over the cuckoo's nest, enjoying the panorama.

      Peace. Empathy. Metaphysics.
    skills:
      enable: true
      title: "Fluently speaking and writing:"
      items:
        - "English"
        - "Russian"
        - "Ukrainian"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Independent Writer"
        company: "Freelance"
        companyUrl: "https://bipoliarnayazvezda.github.io"
        date: "Nov 2010 - present"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        content: ""

      - job: "Freelance Copyeditor"
        company: "TemplateMonster"
        companyUrl: "https://www.templatemonster.com/"
        date: "September 2016 - July 2020"
        featuredLink:
          enable: false
          url: "https://www.templatemonster.com/"
        info:
          enable: false
          content: I worked as a software developer for more than one year in Amazon.
        content: ""

      - job: "Independent Writer"
        company: "Envato"
        companyUrl: "https://www.envato.com/"
        date: "March 2017 - June 2020"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: ""

      - job: "Content Writer"
        company: "Govitall"
        companyUrl: "https://govitall.com/"
        date: "July 2018 - October 2019"
        featuredLink:
          enable: false
          url: "https://example.com"
        content: Content creator, news writer, editor, recent trends expert, etc.

      # - job: "Product Designer"
      #   company: "Google"
      #   companyUrl: "https://example.com"
      #   date: "Feb 2016 - Mar 2017"
      #   content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  # Education
  education:
    enable: false
    # title: "Custom Name"
    index: false
    items:
      - title: "Master of Business Administration"
        school:
          name: "University of California, Berkeley"
          url: "https://example.org"
        date: "2013 - 2015"
        GPA: "3.8 out of 5.0"
        content: |-
          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
      - title: "Bachelor of Science in Computer Science"
        school:
          name: "Massachusetts Institute of Technology"
          url: "https://example.org"
        date: "2009 - 2013"
        GPA: "3.9 out of 5.0"
        content: |-
          I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
          - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
          - Face mask detection using a single convolutional neural network.

          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        featuredLink:
          enable: true
          name: "My academic record"
          url: "https://example.com"
      - title: "High School"
        school:
          name: "Thomas Jefferson High School for Science and Technology."
          url: "https://example.org"
        GPA: "4.2 out of 5.0"
        featuredLink:
          enable: true
          url: "https://example.com"

  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    title: "Books"
    items:
      - title: Voice of a traumatized generation
        content: 
        image: ""
        featured:
          name: Read book
          link: https://bipoliarnayazvezda.github.io/voice/
        links:
          - icon: fa fa-book
            url: https://bipoliarnayazvezda.github.io/voice/voice.epub
          - icon: fa fa-file-word
            url: https://bipoliarnayazvezda.github.io/voice/voice.docx
          - icon: fa fa-file-pdf
            url: https://bipoliarnayazvezda.github.io/voice/voice.pdf
      - title: Aim for the moon
        content:
        image: ""
        featured:
          name: Read book
          link: https://bipoliarnayazvezda.github.io/moon/
        links:
          - icon: fa fa-book
            url: https://bipoliarnayazvezda.github.io/moon/moon.epub
          - icon: fa fa-file-word
            url: https://bipoliarnayazvezda.github.io/moon/moon.docx
          - icon: fa fa-file-pdf
            url: https://bipoliarnayazvezda.github.io/moon/moon.pdf
      - title: We are glad to see you at the funeral services bureau "Pendulum"
        content:
        image: ""
        featured:
          name: Read book
          link: https://bipoliarnayazvezda.github.io/pendulum/
        links:
          - icon: fa fa-book
            url: https://bipoliarnayazvezda.github.io/pendulum/pendulum.epub
          - icon: fa fa-file-word
            url: https://bipoliarnayazvezda.github.io/pendulum/pendulum.docx
          - icon: fa fa-file-pdf
            url: https://bipoliarnayazvezda.github.io/pendulum/pendulum.pdf
      - title: Insomnia
        content: ""
        image: ""
        featured:
          name: Read book
          link: https://bipoliarnayazvezda.github.io/insomnia/
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fa fa-book
            url: https://bipoliarnayazvezda.github.io/insomnia/insomnia.epub
          - icon: fa fa-file-word
            url: https://bipoliarnayazvezda.github.io/insomnia/insomnia.docx
          - icon: fa fa-file-pdf
            url: https://bipoliarnayazvezda.github.io/insomnia/insomnia.pdf

      - title: When I was autopsied in the morgue
        content: Charming detective Ichabod Hart successfully investigates the most intricate murders.
        image: ""
        featured:
          name: Buy
          link: https://www.labirint.ru/books/501842/
        badges:
          - "Detective"
          - "Noir"
        # links:
        #   - icon: fab fa-github
        #     url: https://github.com/gurusabarish/converter

      # - title: Hugo Profile V2
      #   content: A clean and simple Hugo template for personal portfolio and blog.
      #   image: /images/projects/profile2.jpg
      #   featured:
      #     name: Demo V2
      #     link: https://hugo-profile-2.netlify.app
      #   badges:
      #     - "Hugo"
      #     - "Bootstrap"
      #     - "Javascript"
      #   links:
      #     - icon: fab fa-github
      #       url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: alexandra.bulgakova.writer@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Blog
      enable: true
      disableFeaturedImage: true
    socialNetworks:
      #github: https://github.com
      linkedin: https://www.linkedin.com/in/xandracurtis
      #twitter: https://twitter.com
      instagram: https://www.instagram.com/bipoliarnaya.zvezda/
      #facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"

  # For translations
  terms:
    read: "Read"
    toc: "Index"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"
    social: "Share"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
